insert into public.jet_skis (
  slug, name, brand, model, year, type, location, area, coordinate_x, coordinate_y,
  passengers, horsepower, price_per_day, weekend_price, delivery_fee, deposit,
  service_fee, distance_km, rating, reviews, delivery_available, cancellation,
  status, host_name, host_avatar, host_rating, host_response_time, host_verified,
  host_phone, images, features, equipment, rules, description, navigation_zone
)
values
(
  'sea-doo-gtx-170-britannia',
  'Sea-Doo GTX 170 Signature',
  'Sea-Doo',
  'GTX 170',
  2024,
  'Premium',
  'Britannia Beach',
  'Ottawa River',
  41,
  47,
  3,
  170,
  320,
  360,
  55,
  750,
  42,
  8,
  4.96,
  42,
  true,
  'Flexible',
  'active',
  'Maya Tremblay',
  'MT',
  4.98,
  '12 min',
  true,
  '+1 613 555 0148',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg',
    'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80'
  ],
  array['Mode éco', 'Cruise control', 'Compartiment étanche', 'Sonde profondeur'],
  array['Gilets VFI', 'Corde de remorquage', 'Sac étanche', 'Trousse de sécurité'],
  array['Permis bateau ou carte de conducteur obligatoire', 'Retour avec le plein', 'Navigation entre Britannia et Parc Jacques-Cartier'],
  $$Un GTX très stable, confortable à deux ou trois passagers, parfait pour une sortie premium sur la rivière des Outaouais. Idéal pour découvrir les quais, les plages et les zones calmes avec une conduite souple.$$,
  $$Zone recommandée : Britannia Beach, Deschênes Rapids et section balisée vers Aylmer.$$
),
(
  'yamaha-vx-cruiser-aylmer',
  'Yamaha VX Cruiser Aylmer',
  'Yamaha',
  'VX Cruiser HO',
  2023,
  'Familial',
  'Aylmer Marina',
  'Gatineau',
  31,
  54,
  3,
  125,
  280,
  315,
  45,
  650,
  36,
  14,
  4.88,
  31,
  true,
  'Modérée',
  'active',
  'Olivier Paquette',
  'OP',
  4.91,
  '24 min',
  true,
  '+1 819 555 0192',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80'
  ],
  array['Siège confort', 'Échelle arrière', 'Mode débutant', 'Grand coffre'],
  array['3 gilets', 'Ancre légère', 'Carte nautique', 'Bluetooth étanche'],
  array['Minimum 21 ans', 'Briefing de 15 minutes inclus', $$Aucune sortie en cas d'orage annoncé$$],
  $$Un WaveRunner fiable et rassurant, très apprécié par les familles et les couples qui veulent une journée simple, sécurisée et agréable près d'Aylmer.$$,
  $$Zone recommandée : Aylmer, baie de Deschênes et corridors calmes côté Gatineau.$$
),
(
  'sea-doo-spark-trixx-lac-leamy',
  'Sea-Doo Spark Trixx',
  'Sea-Doo',
  'Spark Trixx',
  2022,
  'Sport',
  'Lac Leamy',
  'Gatineau',
  61,
  34,
  2,
  90,
  220,
  250,
  35,
  500,
  28,
  5,
  4.84,
  27,
  false,
  'Flexible',
  'active',
  'Nadia Bisson',
  'NB',
  4.87,
  '18 min',
  true,
  '+1 819 555 0177',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80'
  ],
  array['Mode sport', 'Guidon ajustable', 'Trim étendu', 'Coque légère'],
  array['2 gilets', 'Sifflet', 'Ligne flottante', 'Bidon sécurité'],
  array['Expérience recommandée', 'Pas de figures près des quais', 'Zone de pratique indiquée au départ'],
  $$Compact, joueur et très réactif. Le Spark Trixx est parfait pour une sortie sportive courte avec des sensations immédiates.$$,
  $$Zone recommandée : départ Lac Leamy avec navigation calme selon les conditions locales.$$
),
(
  'kawasaki-ultra-chelsea',
  'Kawasaki Ultra LX Chelsea',
  'Kawasaki',
  'Ultra LX',
  2021,
  'Débutant',
  'Chelsea',
  'Gatineau Hills',
  71,
  22,
  3,
  160,
  260,
  300,
  60,
  600,
  34,
  19,
  4.79,
  19,
  true,
  'Modérée',
  'active',
  'Samuel Leduc',
  'SL',
  4.82,
  '31 min',
  true,
  '+1 873 555 0115',
  array[
    'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80',
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg'
  ],
  array['Mode lent', 'Plateforme large', 'Rangement avant', 'Stabilité renforcée'],
  array['3 gilets', 'GPS portable', 'Kit premiers soins', 'Protection téléphone'],
  array['Briefing obligatoire', 'Navigation lente dans les zones de quai', 'Livraison possible sur quai privé vérifié'],
  $$Un modèle stable et simple à prendre en main. Très bon choix pour une première location accompagnée d'un briefing clair.$$,
  $$Zone recommandée : secteurs calmes validés avec le propriétaire selon le quai choisi.$$
),
(
  'yamaha-fx-ho-parc-jacques-cartier',
  'Yamaha FX HO Parc',
  'Yamaha',
  'FX HO',
  2024,
  'Premium',
  'Parc Jacques-Cartier',
  'Gatineau',
  55,
  43,
  3,
  180,
  340,
  390,
  50,
  800,
  45,
  3,
  4.99,
  53,
  true,
  'Flexible',
  'active',
  'Claire Morin',
  'CM',
  5.00,
  '9 min',
  true,
  '+1 613 555 0188',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg'
  ],
  array['Écran couleur', 'Audio marine', 'Régulateur', 'Confort longue distance'],
  array['3 gilets premium', 'Glacière souple', 'Sac sec', 'Radio VHF'],
  array['Carte conducteur obligatoire', 'Pas de remorquage sans autorisation', 'Assurance et dépôt validés avant départ'],
  $$Une expérience haut de gamme pour longer la rive entre Ottawa et Gatineau avec confort, stabilité et beaucoup de rangement.$$,
  $$Zone recommandée : Parc Jacques-Cartier, Musée canadien de l'histoire et boucles panoramiques balisées.$$
),
(
  'sea-doo-wake-pro-ottawa-river',
  'Sea-Doo Wake Pro 230',
  'Sea-Doo',
  'Wake Pro 230',
  2023,
  'Sport',
  'Ottawa River',
  'Centre-ville',
  48,
  52,
  3,
  230,
  360,
  410,
  65,
  900,
  48,
  6,
  4.90,
  24,
  true,
  'Stricte',
  'active',
  'Karim Haddad',
  'KH',
  4.93,
  '16 min',
  true,
  '+1 613 555 0161',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg'
  ],
  array['Mât wake', 'Mode ski', 'Audio', 'Plateforme LinQ'],
  array['Gilets sport', 'Corde wake', 'Miroir', 'Sac étanche'],
  array['Expérience requise', 'Wake autorisé seulement dans les zones permises', 'Inspection coque au retour'],
  $$Puissant, stable et équipé pour les amateurs de sensations. Idéal pour une sortie sportive encadrée sur l'Outaouais.$$,
  $$Zone recommandée : Ottawa River, avec wake uniquement dans les sections autorisées et dégagées.$$
),
(
  'yamaha-superjet-britannia-compact',
  'Yamaha SuperJet Compact',
  'Yamaha',
  'SuperJet',
  2022,
  'Sport',
  'Britannia Beach',
  'Ottawa River',
  38,
  44,
  1,
  100,
  210,
  240,
  30,
  500,
  26,
  9,
  4.76,
  18,
  false,
  'Flexible',
  'active',
  'Etienne Roy',
  'ER',
  4.80,
  '22 min',
  true,
  '+1 613 555 0133',
  array[
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80'
  ],
  array['Format solo', 'Coque agile', 'Mode sport', 'Faible consommation'],
  array['Gilet sport', 'Sifflet', 'Ligne flottante', 'Sac sec compact'],
  array['Expérience nautique recommandée', 'Départ seulement depuis Britannia Beach', 'Aucune navigation après 18:00'],
  $$Un jet-ski solo agile pour les pilotes qui veulent une sortie courte, vive et facile à organiser à Britannia Beach.$$,
  $$Zone recommandée : boucle locale autour de Britannia Beach selon les conditions de courant.$$
),
(
  'sea-doo-fishpro-aylmer',
  'Sea-Doo FishPro Scout',
  'Sea-Doo',
  'FishPro Scout',
  2023,
  'Familial',
  'Aylmer',
  'Gatineau',
  28,
  58,
  3,
  130,
  295,
  335,
  50,
  700,
  38,
  15,
  4.86,
  22,
  true,
  'Modérée',
  'active',
  'Laurence Gauthier',
  'LG',
  4.90,
  '19 min',
  true,
  '+1 819 555 0126',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg',
    'https://images.unsplash.com/photo-1517400508447-f8dd518b86db?auto=format&fit=crop&w=1400&q=80',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80'
  ],
  array['Plateforme stable', 'Glacière LinQ', 'Échosondeur', 'Mode randonnée'],
  array['3 gilets', 'Glacière', 'Trousse sécurité', 'Support téléphone'],
  array['Navigation familiale uniquement', 'Retour avec carburant au niveau initial', 'Livraison possible à Aylmer et environs'],
  $$Un modèle stable et pratique pour une journée tranquille, avec rangement, glacière et confort pour trois passagers.$$,
  $$Zone recommandée : Aylmer Marina et zones calmes de la rive gatinoise.$$
),
(
  'kawasaki-stx-160-lac-leamy',
  'Kawasaki STX 160 Lac Leamy',
  'Kawasaki',
  'STX 160',
  2024,
  'Débutant',
  'Lac Leamy',
  'Gatineau',
  63,
  31,
  3,
  160,
  275,
  305,
  40,
  620,
  35,
  4,
  4.92,
  29,
  true,
  'Flexible',
  'active',
  'Amine Barka',
  'AB',
  4.94,
  '14 min',
  true,
  '+1 819 555 0184',
  array[
    'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80',
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/2021_RecDeck_Platform_01.jpg'
  ],
  array['Mode confort', 'Stabilité élevée', 'Échelle arrière', 'Rangement avant'],
  array['3 gilets', 'Carte locale', 'Ancre légère', 'Trousse premiers soins'],
  array['Briefing débutant inclus', 'Respect des zones lentes', 'Sortie annulée si vent trop fort'],
  $$Un excellent choix pour débuter avec un propriétaire très présent au départ et des consignes simples.$$,
  $$Zone recommandée : Lac Leamy et départs encadrés selon la météo du jour.$$
),
(
  'sea-doo-rxp-x-chelsea-premium',
  'Sea-Doo RXP-X 300',
  'Sea-Doo',
  'RXP-X 300',
  2024,
  'Premium',
  'Chelsea',
  'Gatineau Hills',
  74,
  26,
  2,
  300,
  420,
  480,
  75,
  1000,
  55,
  21,
  4.97,
  16,
  true,
  'Stricte',
  'active',
  'Victor Nguyen',
  'VN',
  4.99,
  '11 min',
  true,
  '+1 873 555 0199',
  array[
    'https://upload.wikimedia.org/wikipedia/commons/1/17/Couple_of_teenagers_riding_a_jetski_splashing_on_the_Mekong_in_Laos.jpg',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80'
  ],
  array['300 hp', 'Mode sport avancé', 'Siège performance', 'Frein intelligent'],
  array['2 gilets premium', 'Sac étanche', 'Radio VHF', 'Inspection départ'],
  array['Expérience avancée obligatoire', 'Dépôt validé avant livraison', 'Navigation sportive seulement en zone dégagée'],
  $$Une machine premium très puissante pour pilotes expérimentés qui veulent une sortie haut de gamme et encadrée.$$,
  $$Zone recommandée : itinéraire validé avec le propriétaire selon le point de livraison.$$
)
on conflict (slug) do nothing;
